// import { Tiro_Bangla } from "next/font/google"
import "./globals.css";

// const tiroBangal = Tiro_Bangla({
//   variable: "--font-tiro_Bangal",
//   subsets: ["latin"],
//   weight: ["400", "800"],
// })

export const metadata = {
  title: "Kalkini Syed Abul Hossen College",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="bn">
      <body
        // className={`${tiroBangal.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
