import { Geist, Geist_Mono, Tiro_Bangla } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const tiroBangal = Tiro_Bangla({
//   variable: "--font-tiro_bangla",
//   subsets: ["latin"],
// })

export const metadata = {
  title: "Kalkini Syed Abul Hossen College",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="bn">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
